server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    username: ""
    password: ""
    url: "jdbc:h2:./taskTracker"
    
  jpa:
    hibernate:                        
      ddl-auto: create-drop  

  jpa:
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2console
      settings:
        web-allow-others: true

logging:
  level:
    root: INFO
    web: DEBUG
