server:
  port: ${PORT:5000}

spring:
  application:
    name: taskTracker

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    hibernate:                        
      ddl-auto: create-drop
