server:
  error:
    include-stacktrace: never

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://"

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: false

logging:
  level:
    ROOT: INFO
