server:
  error:
    include-stacktrace: never
      
  jpa:
    hibernate:                        
      ddl-auto: create

    show-sql: false      

  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}

logging:
  level:
    ROOT: INFO
