server:
  port: ${PORT}
  error:
    include-stacktrace: never

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  datasource:
    username: ${PGUSER}
    password: ${PGPASSWORD}
    url: "jdbc:${{DATABASE_URL}}"

  jpa:
    show-sql: false

logging:
  level:
    ROOT: INFO
