server:
  error:
    include-stacktrace: never

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  datasource:
    url: "jdbc:postgresql://0.0.0.0:5432"

  jpa:
    show-sql: false

logging:
  level:
    ROOT: INFO
