server:
  port: ${PORT}
  error:
    include-stacktrace: never

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  datasource:
    database: ${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    port: ${PGPORT}
    host: ${PGHOST}
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://${{ PGUSER }}:${{ PGPASSWORD }}@${{ PGHOST }}:${{ PGPORT }}/${{ PGDATABASE }}"

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: false

logging:
  level:
    ROOT: INFO
