server:
  port: ${PORT:5000}

base-url: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  application:
    name: taskTracker

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  mvc:
    hiddenmethod:
      filter:
        enabled: true
      