server:
  port: ${PORT}
  error:
    include-stacktrace: never

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://postgres:xC8Hnje6vRAv3otyaACi@containers-us-west-17.railway.app:6923/railway"

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: false

logging:
  level:
    ROOT: INFO
